CREATE DATABASE ArtWork

CREATE TABLE MUSEUM(
Id_Museum INT PRIMARY KEY,
MuseumName NVARCHAR(60) NOT NULL,
City NVARCHAR(30) NOT NULL
)

CREATE TABLE ARTIST(
Id_Artist INT PRIMARY KEY,
[Name] NVARCHAR(40) NOT NULL,
Country NVARCHAR(30) NOT NULL
)

CREATE TABLE [CHARACTER](
Id_Character INT PRIMARY KEY,
[Name] NVARCHAR(30) NOT NULL
)

CREATE TABLE ARTWORK(
ID_Artwork INT PRIMARY KEY,
[Name] NVARCHAR(40) NOT NULL,
ID_Museum INT NOT NULL FOREIGN KEY REFERENCES MUSEUM(Id_Museum),
ID_Artist INT NOT NULL FOREIGN KEY REFERENCES ARTIST(Id_Artist),
ID_Character INT NULL FOREIGN KEY REFERENCES [CHARACTER] (Id_Character)
)
